[env]
    TERM="xterm-256color"


[window]
    decorations = "Full"
    opacity = 0.95
    dynamic_title = true
    decorations_theme_variant = "None"

[font]
    normal = { family="Hack Nerd Font Mono", style="Regular" }
    size = 12

# Default colors
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

[selection]
    save_to_clipboard=true

[cursor]
    style={shape="Beam", blinking= "On"}
